// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrendSentinel.Infrastructure.Persistence;

#nullable disable

namespace TrendSentinel.Infrastructure.Migrations
{
    [DbContext(typeof(TrendSentinelDbContext))]
    [Migration("20260306124921_Refactor_NewsLog_ValueObjects")]
    partial class Refactor_NewsLog_ValueObjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrendSentinel.Domain.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsAlertSent")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Sector")
                        .HasColumnType("integer");

                    b.Property<string>("TickerSymbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.EventTechnicalSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AboveAvgDaysLast5")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsOverextended")
                        .HasColumnType("boolean");

                    b.Property<string>("MacdState")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NewsLogId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RsiValue")
                        .HasColumnType("numeric");

                    b.Property<int>("TechScore")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("VolRatio")
                        .HasColumnType("numeric");

                    b.Property<string>("VolTrend")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("NewsLogId")
                        .IsUnique();

                    b.ToTable("EventTechnicalSnapshots");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.NewsLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CompanyId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("NewsLogs");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.PriceHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Close")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("High")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Low")
                        .HasColumnType("numeric");

                    b.Property<Guid>("NewsLogId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Open")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("NewsLogId")
                        .IsUnique();

                    b.ToTable("PriceHistories");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.EventTechnicalSnapshot", b =>
                {
                    b.HasOne("TrendSentinel.Domain.Entities.NewsLog", "NewsLog")
                        .WithOne("TechnicalSnapshot")
                        .HasForeignKey("TrendSentinel.Domain.Entities.EventTechnicalSnapshot", "NewsLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsLog");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.NewsLog", b =>
                {
                    b.HasOne("TrendSentinel.Domain.Entities.Company", "Company")
                        .WithMany("NewsLogs")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("TrendSentinel.Domain.ValueObjects.AiAnalysisResult", "Analysis", b1 =>
                        {
                            b1.Property<Guid>("NewsLogId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ConfidenceScore")
                                .HasColumnType("integer")
                                .HasColumnName("Analysis_ConfidenceScore");

                            b1.Property<bool>("IsTrendTriggered")
                                .HasColumnType("boolean")
                                .HasColumnName("Analysis_IsTrendTriggered");

                            b1.Property<string>("Sentiment")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Analysis_Sentiment");

                            b1.Property<string>("TrendSummary")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("Analysis_TrendSummary");

                            b1.HasKey("NewsLogId");

                            b1.ToTable("NewsLogs");

                            b1.WithOwner()
                                .HasForeignKey("NewsLogId");
                        });

                    b.OwnsOne("TrendSentinel.Domain.ValueObjects.QuantSignalMetrics", "QuantMetrics", b1 =>
                        {
                            b1.Property<Guid>("NewsLogId")
                                .HasColumnType("uuid");

                            b1.Property<string>("EventType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Quant_EventType");

                            b1.Property<string>("ExpectedDirection")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Quant_ExpectedDirection");

                            b1.Property<int>("ImpactStrength")
                                .HasColumnType("integer")
                                .HasColumnName("Quant_ImpactStrength");

                            b1.Property<bool>("OverextendedRisk")
                                .HasColumnType("boolean")
                                .HasColumnName("Quant_OverextendedRisk");

                            b1.Property<string>("TimeHorizon")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("Quant_TimeHorizon");

                            b1.HasKey("NewsLogId");

                            b1.ToTable("NewsLogs");

                            b1.WithOwner()
                                .HasForeignKey("NewsLogId");
                        });

                    b.Navigation("Analysis");

                    b.Navigation("Company");

                    b.Navigation("QuantMetrics");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.PriceHistory", b =>
                {
                    b.HasOne("TrendSentinel.Domain.Entities.NewsLog", "NewsLog")
                        .WithOne("PriceSnapshot")
                        .HasForeignKey("TrendSentinel.Domain.Entities.PriceHistory", "NewsLogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NewsLog");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.Company", b =>
                {
                    b.Navigation("NewsLogs");
                });

            modelBuilder.Entity("TrendSentinel.Domain.Entities.NewsLog", b =>
                {
                    b.Navigation("PriceSnapshot");

                    b.Navigation("TechnicalSnapshot");
                });
#pragma warning restore 612, 618
        }
    }
}
